

const Roles = {
  SENIOR_DOCTOR: 1,
  JUNIOR_DOCTOR: 2,
  STAFF_MANAGER: 3,
  JUNIOR_STAFF: 4,
  LABORATORY: 5,
  PHARMACY: 6,
};

const LAB_TEST_TYPE = {
  X_RAY: 0,
  PHYSIOTHERAPY: 1,
  BLOOD_TEST: 3,
  URINE_TEST: 4,
  ECG: 5,
  MRI: 6,
  CT_SCAN: 7,
  ULTRASOUND: 8,
  ENDOSCOPY: 9,
  COLONOSCOPY: 10,
  EEG: 11, // ELECTROENCEPHALOGRAM
  EMG: 12, // ELECTROMYOGRAPHY
  BONE_DENSITY_SCAN: 13,
  MAMMOGRAPHY: 14,
  ALLERGY_TEST: 15,
  CARDIAC_STRESS_TEST: 16,
  ECHOCARDIOGRAM: 17,
  HOLTER_MONITORING: 18,
  SPIROMETRY: 19, // PULMONARY FUNCTION TEST
  BIOPSY: 20, // LIKE: SKIN, LIVER, KIDNEY
  GENETIC_TEST: 21, // FOR HEREDITARY CONDITION
  HORMONE_LEVEL_TEST: 22,
  TUMOR_MARKER: 23, // PSA, CS-125
  LUMBAR_PUNCTURE: 24, // SPINAL TAP
};

module.exports = { Roles, UserType, LAB_TEST_TYPE, StaffUserType };
