# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

volumes:
  orderer.brahma.com:
  peer0.org1.brahma.com:
  peer1.org1.brahma.com:
  peer0.org2.brahma.com:
  peer1.org2.brahma.com:
  peer0.org3.brahma.com:
  peer1.org3.brahma.com:

networks:
  brahma:
    name: fabric_brahma

services:

  orderer.brahma.com:
    container_name: orderer.brahma.com
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7051
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.brahma.com:9443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
        - ../organizations/ordererOrganizations/brahma.com/orderers/orderer.brahma.com/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/brahma.com/orderers/orderer.brahma.com/tls/:/var/hyperledger/orderer/tls
        - orderer.brahma.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7051:7051
      - 9443:9443
    networks:
      - brahma

  peer0.org1.brahma.com:
    container_name: peer0.org1.brahma.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.org1.brahma.com
      - CORE_PEER_ADDRESS=peer0.org1.brahma.com:7052
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.brahma.com:7053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.brahma.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.brahma.com:7052
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org1.brahma.com:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
        - ../organizations/peerOrganizations/org1.brahma.com/peers/peer0.org1.brahma.com:/etc/hyperledger/fabric
        - peer0.org1.brahma.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 7052:7052
      - 9444:9444
    networks:
      - brahma

  peer1.org1.brahma.com:
    container_name: peer1.org1.brahma.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer1.org1.brahma.com
      - CORE_PEER_ADDRESS=peer1.org1.brahma.com:7054
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7054
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.brahma.com:7055
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7055
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.brahma.com:7054
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.brahma.com:7054
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer1.org1.brahma.com:9445
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1org1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
        - ../organizations/peerOrganizations/org1.brahma.com/peers/peer1.org1.brahma.com:/etc/hyperledger/fabric
        - peer1.org1.brahma.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 7054:7054
      - 9445:9445
    networks:
      - brahma

  peer0.org2.brahma.com:
    container_name: peer0.org2.brahma.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.org2.brahma.com
      - CORE_PEER_ADDRESS=peer0.org2.brahma.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.brahma.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.brahma.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.brahma.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp      
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org2.brahma.com:9446
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org2"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
        - ../organizations/peerOrganizations/org2.brahma.com/peers/peer0.org2.brahma.com:/etc/hyperledger/fabric
        - peer0.org2.brahma.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 9051:9051
      - 9446:9446
    networks:
      - brahma


  peer1.org2.brahma.com:
    container_name: peer1.org2.brahma.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer1.org2.brahma.com
      - CORE_PEER_ADDRESS=peer1.org2.brahma.com:9053
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9053
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.brahma.com:9054
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9054
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.brahma.com:9053
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.brahma.com:9053
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp      
      - CORE_OPERATIONS_LISTENADDRESS=peer1.org2.brahma.com:9447
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1org2"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
        - ../organizations/peerOrganizations/org2.brahma.com/peers/peer1.org2.brahma.com:/etc/hyperledger/fabric
        - peer1.org2.brahma.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 9053:9053
      - 9447:9447
    networks:
      - brahma

  #------------------CHanges------------------------
  peer0.org3.brahma.com:
    container_name: peer0.org3.brahma.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.org3.brahma.com
      - CORE_PEER_ADDRESS=peer0.org3.brahma.com:9061
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9061
      - CORE_PEER_CHAINCODEADDRESS=peer0.org3.brahma.com:9062
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9062
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.brahma.com:9061
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.brahma.com:9061
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp      
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org3.brahma.com:9456
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org3"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
        - ../organizations/peerOrganizations/org3.brahma.com/peers/peer0.org3.brahma.com:/etc/hyperledger/fabric
        - peer0.org3.brahma.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 9061:9061
      - 9456:9456
    networks:
      - brahma


  peer1.org3.brahma.com:
    container_name: peer1.org3.brahma.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer1.org3.brahma.com
      - CORE_PEER_ADDRESS=peer1.org3.brahma.com:9063
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9063
      - CORE_PEER_CHAINCODEADDRESS=peer1.org3.brahma.com:9064
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9064
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.brahma.com:9063
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org3.brahma.com:9063
      - CORE_PEER_LOCALMSPID=org3MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp      
      - CORE_OPERATIONS_LISTENADDRESS=peer1.org3.brahma.com:9457
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1org3"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
        - ../organizations/peerOrganizations/org3.brahma.com/peers/peer1.org3.brahma.com:/etc/hyperledger/fabric
        - peer1.org3.brahma.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 9063:9063
      - 9457:9457
    networks:
      - brahma
  #---------------------------------------
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.org1.brahma.com
      - peer1.org1.brahma.com
      - peer0.org2.brahma.com
      - peer1.org2.brahma.com
      - peer0.org3.brahma.com
      - peer1.org3.brahma.com
    networks:
      - brahma
